export interface image {
    collections:number
    comments:number
    downloads:number
    id:number
    imageHeight:number
    imageSize:number
    imageWidth:number
    largeImageURL:string
    likes:number
    pageURL:number
    previewHeight:number
    previewURL:string
    previewWidth:number
    tags:string
    tagsArray?:any 
    type:string
    user:string
    userImageURL:string
    user_id:number
    views:number
    webformatHeight:number
    webformatURL:string
    webformatWidth:number
}